fun main() {
    try {
        index = '1';
        print('Try');
    } catch(e: Exception) {
        print('Catch');
    } finally {
        print('Finally');
    }
}